# 1. Traer la máquina base con Python, Jupyter y PySpark ya configurados
FROM jupyter/pyspark-notebook:latest

# 2. Instalar Polars de forma limpia sin guardar archivos basura
RUN pip install --no-cache-dir polars
